apiVersion: v1
kind: Service
metadata:
  name: argocd-kind-demo
  namespace: group1-apps
  labels:
    app.kubernetes.io/name: argocd-kind-demo
    app.kubernetes.io/part-of: platform-demo
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-kind-demo
  ports:
    - name: http
      port: 80
      targetPort: http
