apiVersion: v1
kind: Service
metadata:
  name: arc-demo
  namespace: arc-demo
  labels:
    app.kubernetes.io/name: arc-demo
    app.kubernetes.io/part-of: arc-onboarding
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: arc-demo
  ports:
    - name: http
      port: 80
      targetPort: http
