apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-access-policy
  namespace: devtroncd
  labels:
    app.kubernetes.io/name: platform-access-policy
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  aks_cluster_names: gitops-aks
  aks_deploy_namespace: group2-aks-apps
  aks_devtron_app_roles: role:admin_group2-aks-apps_g2-aks_
  kind_cluster_names: arc-demo-vm,arc-demo-vm-2
  kind_deploy_namespace: group1-apps
  kind_devtron_app_roles: role:admin_group1-kind-apps_g1-kind1_,role:admin_group1-kind-apps_g1-kind2_
  backstage_clusters: |
    - name: gitops-aks
      type: aks
      visibilityGroup: akspe-aks-cluster-deployers
      deployNamespace: group2-aks-apps
    - name: arc-demo-vm
      type: kind
      visibilityGroup: akspe-kind-cluster-deployers
      deployNamespace: group1-apps
    - name: arc-demo-vm-2
      type: kind
      visibilityGroup: akspe-kind-cluster-deployers
      deployNamespace: group1-apps
