apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kind-store-demo"
  description: "Demo application deployed to Arc/kind by ArgoCD."
  annotations:
    backstage.io/kubernetes-id: "kind-store-demo"
    backstage.io/source-location: url:https://github.com/zhangchl007/aks-platform-engineering.git
    platform-access.akspe.io/deployment-target: "kind-arc-demo-vms-group1"
spec:
  type: service
  owner: group:default/k8sadmin
  lifecycle: production
  dependsOn:
    - resource:default/arc-demo-vm
    - resource:default/arc-demo-vm-2
