apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "aks-store-demo"
  description: "AKS Store Demo application deployed to AKS by ArgoCD."
  annotations:
    backstage.io/kubernetes-id: "aks-store-demo"
    backstage.io/source-location: url:https://github.com/zhangchl007/aks-platform-engineering.git
    platform-access.akspe.io/deployment-target: "aks-gitops-aks-group2"
spec:
  type: service
  owner: group:default/k8sadmin
  lifecycle: production
  dependsOn:
    - resource:default/gitops-aks
