apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks-store-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    backstage.io/kubernetes-id: aks-store-demo
    platform-access.akspe.io/requested-by: user:default/demouser1
    platform-access.akspe.io/delivery-persona: aks
    platform-access.akspe.io/target-environment: aks-gitops-aks-group2
spec:
  project: aks-team-delivery
  source:
    repoURL: https://github.com/zhangchl007/aks-platform-engineering.git
    targetRevision: zhangchl007-arc-multi-cluster-access
    path: gitops/apps/platform-demo/aks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: group2-aks-apps
    name: gitops-aks
