apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${{ values.name }}
  namespace: argocd
  annotations:
    backstage.io/kubernetes-id: ${{ values.name }}
    platform-access.akspe.io/requested-by: ${{ values.requesterEntityRef }}
    platform-access.akspe.io/delivery-persona: ${{ values.deliveryPersona }}
    platform-access.akspe.io/target-environment: ${{ values.targetEnvironment }}
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            provider: arc
            platform_cluster_type: kind
            platform_access_enabled: "true"
            platform_backstage_delivery_enabled: "true"
  template:
    metadata:
      name: '${{ values.name }}-{% raw %}{{ .name }}{% endraw %}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        backstage.io/kubernetes-id: ${{ values.name }}
        platform-access.akspe.io/requested-by: ${{ values.requesterEntityRef }}
        platform-access.akspe.io/delivery-persona: ${{ values.deliveryPersona }}
        platform-access.akspe.io/target-environment: ${{ values.targetEnvironment }}
    spec:
      project: kind-team-delivery
      source:
        repoURL: ${{ values.appRepoUrl }}
        targetRevision: ${{ values.targetRevision }}
        path: ${{ values.appPath }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: group1-apps
        name: '{% raw %}{{ .name }}{% endraw %}'
