apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-access
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: akspe-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/zhangchl007/aks-platform-engineering
    targetRevision: zhangchl007-arc-multi-cluster-access
    path: gitops/apps/platform-access/manifests
  destination:
    name: gitops-aks
    namespace: platform-access-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
