apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}
  namespace: argocd
  annotations:
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  project: default
  source:
    repoURL: ${{ values.appRepoUrl }}
    targetRevision: ${{ values.targetRevision }}
    path: ${{ values.appPath }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: ${{ values.namespace }}
    server: https://kubernetes.default.svc
